### PyTorch for Deep Learning and Machine Learning
#### https://www.youtube.com/watch?v=V_xro1bcAuA&t=38772s
#### https://www.learnpytorch.io/

# 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

## Introduction to Tensors

### Creating tensors

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
# Get tensor back a Python int
scalar.item()

In [ ]:
# Vector

In [ ]:
vector = torch.tensor([7, 7])

In [ ]:
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

In [ ]:
MATRIX.ndim

In [ ]:
MATRIX[0]

In [ ]:
MATRIX[1]

In [ ]:
MATRIX.shape

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                     [3, 6, 9],
                     [2, 4, 5]]])
TENSOR

In [ ]:
TENSOR.ndim

In [ ]:
TENSOR.shape

In [ ]:
TENSOR[0]

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

In [ ]:
random_tensor

In [ ]:
random_tensor.ndim

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224))  # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

In [ ]:
zeros * random_tensor

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

In [ ]:
ones.dtype

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,  # what datatype is the tensor (e.g. float32 or float16)
                               device = None,  # what device is your tensor on
                               requires_grad = False)  # whether or not to track gradients with this tensor's operations
float_32_tensor

In [ ]:
float_32_tensor.dtype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

In [ ]:
float_16_tensor * float_32_tensor

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

In [ ]:
float_32_tensor * int_32_tensor

### Getting information from tensors

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Size of tensor: {some_tensor.size()}")  # a function, not a method
print(f"Device of tensor is on: {some_tensor.device}")

In [ ]:
some_tensor.shape

In [ ]:
some_tensor.device

### Manipulating tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

In [ ]:
# Multiply tensor by 10
tensor * 10

In [ ]:
tensor

In [ ]:
# Subtract 10
tensor - 10

In [ ]:
# Try out PyTorch built-in functions
torch.mul(tensor, 10)

In [ ]:
torch.add(tensor, 10)

In [ ]:
torch.subtract(tensor, 10)

In [ ]:
torch.divide(tensor, 10)

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

In [ ]:
torch.matmul(torch.rand(3, 10), torch.rand(10, 3))

In [ ]:
# Element-wise multiplication
print(f"{tensor} * {tensor} = {tensor * tensor}")

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

In [ ]:
tensor @ tensor

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

In [ ]:
%time
torch.matmul(tensor, tensor)

#### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [ ]:
# torch.mm(tensor_A, tensor_B)  # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")

print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")

print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)

print(output)

print(f"\nOutput shape: {output.shape}")

## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

In [ ]:
x.dtype

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

In [ ]:
x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

## Finding the positional min and max

In [ ]:
x

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target
# tensor where the minimum value occurs
x.argmin()

In [ ]:
x[0]

In [ ]:
x = torch.arange(1, 100, 10)
x

In [ ]:
x.argmin()

In [ ]:
x[0]

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

In [ ]:
x[9]

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of in input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze - dim = 0
x_unsqueezed_0 = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed_0}")
print(f"New shape: {x_unsqueezed_0.shape}")

# Add an extra dimension with unsqueeze - dim = 1
x_unsqueezed_1 = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed_1}")
print(f"New shape: {x_unsqueezed_1.shape}")

In [ ]:
# torch.permute() - rearranges the dimension of a target tensor in a specified order
x_original = torch.rand(size = (224, 224, 3))  # [height, width, colour channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")  # [colour channels, height, width]

In [ ]:
x_original[0, 0, 0] = 728218
print(x_original[0, 0, 0])
print(x_permuted[0, 0, 0])

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

In [ ]:
# Let's index on our new tensor
x[0]

In [ ]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

In [ ]:
# Let's index on the inner most bracket (last dimension)
x[0][0][0]

In [ ]:
x[0][0][1]

In [ ]:
x[0][1][1]

In [ ]:
x[0][2][2]

In [ ]:
# You can also use ":" to select all of a target dimension

In [ ]:
x[:, 0]

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

In [ ]:
# Get all values of the 0th dimension but only the index value 1 of 1st and 2nd dimensions
x[:, 1, 1]

In [ ]:
x[0, 1, 1]

In [ ]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

In [ ]:
# Index on x to return 9
x[0, 2, 2]

In [ ]:
# Index on to return 3, 6, 9
x[:, :, 2]

## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.

And because of thos, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.tensor.numpy()`

In [3]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  
# warning: when converting from NumPy to PyTorch, PyTorch reflects NumPy's default data type of float64
# unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
array.dtype

dtype('float64')

In [7]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [9]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [11]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [13]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [15]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [17]:
numpy_tensor.dtype

dtype('float32')

In [19]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how neural networks learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

In [30]:
# Create a tensor

torch.rand(3, 3)

# Each time we run this cell, the numbers change.

tensor([[0.0942, 0.4625, 0.2470],
        [0.9911, 0.6498, 0.1740],
        [0.4886, 0.6300, 0.7865]])

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [33]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7061, 0.1361, 0.6878, 0.6752],
        [0.8442, 0.6419, 0.8178, 0.2702],
        [0.6445, 0.0180, 0.3217, 0.2671]])
tensor([[0.6825, 0.4940, 0.4493, 0.3055],
        [0.8222, 0.4441, 0.8920, 0.1401],
        [0.7275, 0.7198, 0.0453, 0.1086]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [35]:
# Let's make some random but reproducible tensors

# Set the random seed
torch.manual_seed(seed = 42)

In [37]:
# Create two random tensors

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [39]:
torch.manual_seed(seed = 42)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed = 42)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch documentation.

Google Colab : Exécution > Modifier le Type d'Exécution > T4 GPU

`!nvidia-smi` to show GPU details

### 2. Check for GPU access with PyTorch

In [49]:
# Check for GPU access with PyTorch

torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code.
e.g. run on GPU if available, else default to CPU.

In [51]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [53]:
# Count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using GPU results in faster computations.

In [59]:
# Create a tensor (default on the CPU)

#tensor = torch.tensor([1, 2, 3], device = "cpu")  # by default on the cpu
tensor = torch.tensor([1, 2, 3])
# Tensor not on GPU

print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [63]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

In [ ]:
tensor_on_gpu

## Exercises and extra-curriculum
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises